### ISSUE TITLE
There are a lot of spare images

### ISSUE THREAD

**Issue by robisaacnz** [WikiNewZealand/pacific#37]
We've changed the way we use the template, so there are a lot of leftover images. @natdudley needs to clean these up.

**Comment by natdudley** [comment]
Working on this on branch bugfix-design-clean

**Comment by natdudley** [comment]
On investigation:

- homepage tiles only use the "List" category. This is an artifact of Places where we used the same photo in the tile list as we did in the page header, and we needed to select the correct version of the image for both based on screen size.
- page headers use the full range of categories. Right now this is only 'About' 'Experts' and 'Reports'. For now, I have removed all of the other images from those folders. Presently, the images in all those folders (pngs) are the same size, making this setup redundant. However, we may want to review this to ensure faster loading on mobile.

@robisaacnz let's talk about this today?
