### ISSUE TITLE
Change to the wording - Samoan words

### ISSUE THREAD

**Issue by Ngapera** [WikiNewZealand/pacific#47]
Jackie has suggested changes to the following copy. 

Data empowers us. “Fa’amaumauga e mafai ai ona faamalosia ai o tatou tagata Pasefika.” - Jackie suggested that this heading might work better in quotation marks, and she would like to add the apostrophes back please.

**Comment by robisaacnz** [comment]
Unattributed quotes (aka "scare quotes") are prohibited by our style guide (and good taste!). We need either someone to quote as saying this, or we need to emphasise this text without including it in quote marks.

**Comment by Ngapera** [comment]
> Unattributed quotes (aka "scare quotes") are prohibited by our style guide (and good taste!). We need either someone to quote as saying this, or we need to emphasise this text without including it in quote marks.

Ka pai, I will let her know. TIL "scare quotes" :)

**Comment by natdudley** [comment]
@robisaacnz would an em dash work? I'm not sure on the grammar rules around that. So, 

```Data empowers us — Fa’amaumauga e mafai ai ona faamalosia ai o tatou tagata Pasefika.```

**Comment by robisaacnz** [comment]
An em dash indicates a continuation of the same sentence, so it's appropriate. A colon is more commonly used to indicate a successive clause of the same sentence where the subject has not changed, so,

`Data empowers us — Fa’amaumauga e mafai ai ona faamalosia ai o tatou tagata Pasefika.`

But I'm happy with either of these as an alternative to scare quotes.

**Comment by natdudley** [comment]
Cool, I'll go with the latter.
