### ISSUE TITLE
Update Dr Ofa's description in the ABOUT THE PROJECT section

### ISSUE THREAD

**Issue by Ngapera** [WikiNewZealand/pacific#48]
In the about section, we need to update Dr Ofa’s wording please (she just sent this edited version through)
A special mihi to Dr Ofa Ketu’u, who gifted us the name of Pacific Data Fale o Aotearoa. Dr Ofa Ketu’u has worked at Statistics NZ for many years, holding managerial roles in different parts of the organisation. She is also a member of the Pacific Data Sovereignty Network. Between 2016-2019, she was also Director of Statistics for Pacific Community (SPC) based in Noumea, New Caledonia. She has very strong knowledge on economic and social statistics for Pacific people and her passion is in making sure that Pacific people use statistics and data to inform decisions that affect their lives on a day-to-day basis. Ofa hails from the Kingdom of Tonga but also consider herself a New Zealand immigrant. She lives in the heart of South Auckland with her whanau. We wanted to acknowledge Dr Ofa’s contribution to this project but also her lifelong passion for Pacific people data and wellbeing

**Comment by natdudley** [comment]
Accidentally closed wrong issue. This will be closed when we merge PR.
