### ISSUE TITLE
Is there somewhere to include the meaning of the name? Pacific Data Fale o Aotearoa

### ISSUE THREAD

**Issue by Ngapera** [WikiNewZealand/pacific#50]
Are we also able to add the story of the name somewhere? It isn't urgent by any means, but just thinking about somewhere to log this. The naming of things is pretty important in Pacific culture, and someone might ask?  - Maybe I add it to the FAQ's? 

How did we get the name Pacific Data Fale o Aotearoa?
Dr Ofa Ketu’u kindly gifted us the name Pacific Data Fale o Aotearoa and provided the following context.
 
(English Translation: Pacific Data House of New Zealand)
(Short Version: Pacific Data Fale)
 
“Fale” means House in multiple Pacific languages and is a widely recognised word in Aotearoa.
 
There were several reasons for selecting this as a title:
 
I’ve included “Aotearoa” to reinforce that this platform focuses on data about Pacific People in New Zealand
I’ve used “Fale” as it’s commonly used among Pacific nations to mean a place of meeting or house to live in. It also refers to a storage place and gives the platform a Pacific flavour.
The title needs to be eye catching and easy to understand not just for Pacific people but also non-Pacific people who are interested in Pacific data.
Audience will normally use keywords such as “Pacific Data”, “Pacific People Data” Data on Pacific People in Aotearoa, etc, when searching for data on Pacific People in NZ.
We loved the name too and are very grateful to Dr Ketu’u.

**Comment by natdudley** [comment]
Yup. Will add to FAQs. I am going to close this issue and move this across to the FAQ issue.
