### ISSUE TITLE
SVG Stripe Issue - iPhone XS Max horizontal view

### ISSUE THREAD

**Issue by natdudley** [WikiNewZealand/pacific#58]
![IMG_0529](https://user-images.githubusercontent.com/3861245/129837652-a54e7aa2-0571-42de-9bdd-c1dcd68c9bb1.PNG)

Still getting issue on phone even after deploy. Can't replicate in Chrome now, nor on desktop safari at similar width.

**Comment by robisaacnz** [comment]
I'm struggling to replicate this. Closest I can get is a (simulated) iPhone 5 in portrait.
![Screen Shot 2021-08-18 at 4 43 35 PM](https://user-images.githubusercontent.com/360402/129838297-dd1ccdd6-5659-4a9b-a4a7-3d160a557ee7.png)

**Comment by natdudley** [comment]
Weirdness. I'll try again. Maybe my phone has something cached??

**Comment by natdudley** [comment]
Closed all the tabs on my phone and re-opened and it works again. So, let's call it done.

Should I try fix for iPhone 5 that you're seeing. Only downside is it might make it hard to click Stats logo.

**Comment by natdudley** [comment]
Given how uncommon iPhone5 is, i'm considering this closed. Reopen if we want to fix.
