### ISSUE TITLE
Please add a link to pacificdata@figure.nz at the bottom of the Pacific Expert data list

### ISSUE THREAD

**Issue by Ngapera** [WikiNewZealand/pacific#65]
Hiya, can you please add a link so people can add their organisations or their names to the list of Pacific data leaders? Thank you   SOmething akong the lines of

To add yourself or your organisation, email us at pacificdata@figure.nz

**Comment by natdudley** [comment]
sent a test email, just to make sure address right. LMK if it arrives.
