### ISSUE TITLE
Please make changes to Dr Ofa Ketu'u on the expert list

### ISSUE THREAD

**Issue by Ngapera** [WikiNewZealand/pacific#68]
Name

Statistical topics

Role / Organisation

Dr Ofa Ketu'u

official statistics on Pacific Peoples

Program Manager Stats NZ Pacific Statistics Support Program,

Statistics NZ Customer Delivery Services

Point of Contact:

Mele Siakumi-Kautoke, Advisor – Customer Information

There is a team within Customer Delivery Services Group that will guide you on where to find official statistics/data on Pacific people

**Comment by Ngapera** [comment]
> Name
> 
> Statistical topics
> 
> Role / Organisation
> 
> Dr Ofa Ketu'u
> 
> official statistics on Pacific Peoples
> 
> Program Manager Stats NZ Pacific Statistics Support Program,
> 
> Statistics NZ Customer Delivery Services
> 
> Point of Contact:
> 
> Mele Siakumi-Kautoke, Advisor – Customer Information
> 
> There is a team within Customer Delivery Services Group that will guide you on where to find official statistics/data on Pacific people

I hope this makes sense @natdudley :)

**Comment by natdudley** [comment]
fixed.
