### ISSUE TITLE
Purchase and optimise Pacific images.

### ISSUE THREAD

**Issue by natdudley** [WikiNewZealand/pacific#7]
Suggested images are listed in: https://docs.google.com/spreadsheets/d/1xFj2G5tFZi_Drnrnhw1vxY_5GpW9ULR8JavMtCVHH0c/edit#gid=1185776153

These need to be purchased and then optimised for web display and added to the hub.

**Comment by robisaacnz** [comment]
This was completed and merged in a different branch.
